brew "fzf"
brew "git"
brew "btop"
brew "htop"
brew "midnight-commander"
brew "neovim"
brew "stow"
brew "tig"
brew "dockutil"
brew "ripgrep"
brew "fd"
brew "tenv"
brew "terraform-ls"
brew "gh"
brew "node"
brew "gsed"
brew "pwgen"
brew "gnupg"
brew "pinentry-mac"
brew "opa"
brew "pure" # zsh prompt

cask "ghostty"
cask "vlc"
cask "logi-options+"
cask "rectangle-pro"
cask "monitorcontrol"
cask "telegram"
cask "forklift"
cask "google-chrome"
cask "microsoft-edge"
cask "scroll-reverser"
cask "spotify"
cask "visual-studio-code"
cask "1password"

# podman
brew "podman"
cask "podman-desktop"

# fonts
tap "homebrew/cask-fonts"
cask "font-sometype-mono"

# anti flickering
cask "stillcolor"
