activeWorkspaceOnFocusChange = true
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = false
checkForUpdatesAutomatically = false
displayMode = 'static'
enableFocusManagement = true
enableIntegrations = false
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSwipeGestures = false
enableWorkspaceTransitions = false
focusDown = 'ctrl+down'
focusFrontmostWindow = false
focusLeft = 'ctrl+left'
focusRight = 'ctrl+right'
focusUp = 'ctrl+up'
keepUnassignedAppsOnSwitch = true
loopWorkspaces = true
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE_NUMBER'
pipApps = []
pipScreenCornerOffset = 15
restartAppOnWakeUp = false
restoreHiddenAppsOnSwitch = true
runScriptOnLaunch = ''
runScriptOnProfileChange = 'sketchybar --reload'
runScriptOnWorkspaceChange = 'sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE" DISPLAY="$DISPLAY"'
showFloatingNotifications = true
showMenuBarIcon = true
showMenuBarTitle = true
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'previousWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'nextWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToRecentWorkspace = 'opt+`'
switchWorkspaceWhenPipCloses = true
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.10000000000000001