activeWorkspaceOnFocusChange = false
alternativeDisplays = ''
centerCursorOnFocusChange = false
centerCursorOnWorkspaceChange = false
changeWorkspaceOnAppAssign = false
checkForUpdatesAutomatically = false
displayMode = 'static'
enableFocusManagement = true
enableIntegrations = true
enablePictureInPictureSupport = true
enableSpaceControl = false
enableSpaceControlAnimations = true
enableSwipeGestures = false
enableWorkspaceTransitions = false
focusDown = 'ctrl+down'
focusFrontmostWindow = false
focusLeft = 'ctrl+left'
focusRight = 'ctrl+right'
focusUp = 'ctrl+up'
keepUnassignedAppsOnSwitch = true
loopWorkspaces = true
menuBarDisplayAliases = ''
menuBarTitleTemplate = '$WORKSPACE_NUMBER'
pipApps = []
pipScreenCornerOffset = 15
restartAppOnWakeUp = false
restoreHiddenAppsOnSwitch = true
runScriptOnLaunch = '~/Projects/dotfiles/bin/.bin/bstrap.sh'
runScriptOnProfileChange = ''
runScriptOnWorkspaceChange = ''
showFloatingNotifications = true
showMenuBarIcon = true
showMenuBarTitle = true
skipEmptyWorkspacesOnSwitch = false
spaceControlCurrentDisplayWorkspaces = false
spaceControlMaxColumns = 6
swipeDown3FingerAction = 'none'
swipeDown4FingerAction = 'none'
swipeLeft3FingerAction = 'previousWorkspace'
swipeLeft4FingerAction = 'none'
swipeRight3FingerAction = 'nextWorkspace'
swipeRight4FingerAction = 'none'
swipeThreshold = 0.20000000000000001
swipeUp3FingerAction = 'none'
swipeUp4FingerAction = 'none'
switchToRecentWorkspace = 'opt+`'
switchWorkspaceWhenPipCloses = true
workspaceTransitionDimming = 0.20000000000000001
workspaceTransitionDuration = 0.10000000000000001

[[floatingApps]]
bundleIdentifier = 'com.apple.Notes'
iconPath = '/System/Applications/Notes.app/Contents/Resources/AppIcon.icns'
name = 'Notes'

[[floatingApps]]
bundleIdentifier = 'com.openai.chat'
iconPath = '/Applications/ChatGPT.app/Contents/Resources/AppIcon.icns'
name = 'ChatGPT'

[[floatingApps]]
bundleIdentifier = 'com.lujjjh.LinearMouse'
iconPath = '/Applications/LinearMouse.app/Contents/Resources/AppIcon.icns'
name = 'LinearMouse'