osx_defaults:
  - name: Short delay until repeat
    key: InitialKeyRepeat
    value: 15
    type: integer

  - name: Fast key repeat
    key: KeyRepeat
    value: 2
    type: integer

  - name: Disable automatic correction of spelling
    key: NSAutomaticSpellingCorrectionEnabled
    value: 0
    type: integer

  - name: Disable smart quotes
    key: NSAutomaticQuoteSubstitutionEnabled
    value: 0
    type: integer

  - name: Disable smart dashes
    key: NSAutomaticDashSubstitutionEnabled
    value: 0
    type: integer

  - name: Show battery percentage
    domain: com.apple.menuextra.battery
    key: ShowPercent
    value: "YES"
    type: string

  - name: Tap to click
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    value: 1
    type: integer

  - name: Show file extensions
    key: AppleShowAllExtensions
    value: 1
    type: integer

  - name: Show hidden files
    key: AppleShowAllFiles
    value: 1
    type: integer

  - name: Search in current folder
    domain: com.apple.finder
    key: FXDefaultSearchScope
    value: SCcf
    type: string

  - name: Display home directory by default - 1
    domain: com.apple.finder
    key: "NewWindowTarget"
    value: "PfHm"
    type: string

  - name: Display home directory by default - 2
    domain: com.apple.finder
    key: "NewWindowTargetPath"
    value: "file:///Users/{{ lookup('env', 'USER') }}/"
    type: string

  - name: Display directories using list view
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: Nlsv
    type: string

  - name: Set size of dock
    domain: com.apple.dock
    key: tilesize
    value: 48
    type: float

  - name: Do not mess dock with recent apps
    domain: com.apple.dock
    key: show-recents
    value: 0
    type: integer

  - name: Minimise windows to their app icons
    domain: com.apple.dock
    key: minimize-to-application
    value: true
    type: boolean

  - name: Disable open/close windows animations
    domain: NSGlobalDomain
    key: NSAutomaticWindowAnimationsEnabled
    value: false
    type: boolean

  - name: Disable quick view opening animation
    key: QLPanelAnimationDuration
    value: 0
    type: float

  - name: Disable finder info animations
    domain: com.apple.finder
    key: DisableAllAnimations
    value: true
    type: boolean

  - name: Disable opening from dock animation
    domain: com.apple.dock
    key: launchanim
    value: false
    type: boolean

  - name: Set minimise effect
    domain: com.apple.dock
    key: mineffect
    value: genie
    type: string

  - name: Set time format
    domain: com.apple.menuextra.clock
    key: DateFormat
    value: EEE HH:mm
    type: string

  # iTerm2

  - name: Show tab bar even when there is only one tab
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: HideTab
    value: 0
    type: integer

  - name: Compact theme
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: TabStyleWithAutomaticOption
    value: 5
    type: integer

  - name: Do not disable GPU rendered when disconnected from power
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: disableMetalWhenUnplugged
    value: 0
    type: integer

  - name: Do not show window number in title bar
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: WindowNumber
    value: 0
    type: integer

  - name: Hide scrollbars
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: HideScrollbar
    value: 1
    type: integer

  - name: Do not show tabs close button
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: TabsHaveCloseButton
    value: 0
    type: integer

  - name: Disable session restoration
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: RunJobsInServers
    value: 0
    type: integer

  - name: Automatic updates
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: SUEnableAutomaticChecks
    value: 1
    type: integer

  - name: Use my profile from git as default
    domain: ~/Library/Preferences/com.googlecode.iterm2
    key: Default Bookmark Guid
    value: 5E5ADF35-3E76-498C-A7A1-53DE3BCA8A12
    type: string
