- hosts:
    - localhost
  connection: local
  roles:
    - krzysztof-magosa.homebrew
  tasks:
    - name: Set osx defaults
      osx_defaults:
        domain: "{{ item.domain | default(omit) }}"
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        type: "{{ item.type }}"
      loop: "{{ osx_defaults }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - osx_defaults

    - name: Install virtualenvwrapper
      pip:
        name: virtualenvwrapper
        extra_args: "--user"
      tags:
        - pip

    - name: Configure dock icons
      command: "dockutil --{{ item.state }} {{ item.icon }}"
      loop: "{{ dock_icons }}"
      tags:
        - dock_icons
